import { supabase } from './supabase-client.js?v=1.0.1';
import { createGenericEditor, editorValue, sanitizeRichHtml } from './generic-editor.js?v=1.3.2';

const detailDialog=document.querySelector('#detailDialog');
const courses=['','Breakfast','Brunch','Starter','Soup','Salad','Main','Side','Snack','Dessert','Bread','Beverage','Ingredient'];
const types=['','Dish','Dip','Dressing','Sauce','Chutney','Marinade','Rub','Paste','Spice Blend','Stock / Broth','Pickle','Condiment'];
const cuisines=['','Indian','Chinese','Japanese','Korean','Thai','Malay','Vietnamese','Mexican','Italian','French','Spanish','Greek','Mediterranean','Middle Eastern','American','British','Other / custom…'];
const state={cuisine:'',course:'',type:'',country:'',favourite:false,sort:'latest'};
let lastLibrarySignature='';

function esc(s=''){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function ingredientHtml(r){const a=r?.ingredients;if(a&&typeof a==='object'&&!Array.isArray(a)&&typeof a.html==='string')return sanitizeRichHtml(a.html);if(Array.isArray(a))return a.map(x=>typeof x==='string'?esc(x):esc([x?.quantity,x?.unit,x?.name].filter(Boolean).join(' '))).join('<br>');return esc(a||'')}
function distinct(field){return [...new Set((window.ccRecipes||[]).map(r=>String(r?.[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function selectHtml(name,label,options,value,allLabel='All'){return `<label class="library-filter"><span>${esc(label)}</span><select data-filter="${name}"><option value="">${esc(allLabel)}</option>${options.map(o=>`<option value="${esc(o)}" ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`}
function renderRecipeTools(){const content=document.querySelector('#content');if(!content)return;const head=content.querySelector('.section-head');if(!head)return;document.querySelector('#ccLibraryTools')?.remove();const tools=document.createElement('div');tools.id='ccLibraryTools';tools.innerHTML=`<div class="library-actions"><button class="secondary" id="ccImportRecipes" type="button">Import recipes</button><button class="primary" id="ccNewRecipe" type="button">＋ New recipe</button></div><div class="library-heading-row"></div>`;head.parentNode.insertBefore(tools,head);document.querySelector('#ccImportRecipes').onclick=()=>document.querySelector('#importBtn')?.click();document.querySelector('#ccNewRecipe').onclick=()=>window.ccOpenNewRecipeEditor?.();}
function renderRecipeFilters(){const content=document.querySelector('#content');const head=content?.querySelector('.section-head');if(!head)return;document.querySelector('#ccRecipeFilters')?.remove();const filters=document.createElement('div');filters.id='ccRecipeFilters';const cuisine=[...new Set([...cuisines.filter(Boolean),...distinct('cuisine')])].sort();const course=[...new Set([...courses.filter(Boolean),...distinct('course')])].sort();const type=[...new Set([...types.filter(Boolean),...distinct('recipe_type')])].sort();const regions=[...new Set([...distinct('country'),...distinct('region')])].sort();filters.innerHTML=`${selectHtml('cuisine','Cuisine',cuisine,state.cuisine)}${selectHtml('course','Course',course,state.course)}${selectHtml('type','Recipe type',type,state.type)}${selectHtml('country','Country / Region',regions,state.country)}<label class="library-filter"><span>Favourites</span><select data-filter="favourite"><option value="">All</option><option value="yes" ${state.favourite?'selected':''}>Favourites</option></select></label><label class="library-filter"><span>Latest</span><select data-filter="sort"><option value="latest" ${state.sort==='latest'?'selected':''}>Latest</option><option value="name" ${state.sort==='name'?'selected':''}>Name A–Z</option><option value="oldest" ${state.sort==='oldest'?'selected':''}>Oldest</option></select></label>`;head.parentNode.insertBefore(filters,head.nextSibling);filters.querySelectorAll('select').forEach(s=>s.onchange=()=>{state[s.dataset.filter]=s.value;if(s.dataset.filter==='favourite')state.favourite=s.value==='yes';applyRecipeFilters()});}
function applyRecipeFilters(){const cards=[...document.querySelectorAll('#content .card')];const data=new Map((window.ccRecipes||[]).map(r=>[Number(r.id),r]));const visible=[];cards.forEach(card=>{const r=data.get(Number(card.dataset.id));if(!r)return;const region=[r.country,r.region].filter(Boolean).join(' / ');const ok=(!state.cuisine||r.cuisine===state.cuisine)&&(!state.course||r.course===state.course)&&(!state.type||r.recipe_type===state.type)&&(!state.country||region===state.country||r.country===state.country||r.region===state.country)&&(!state.favourite||r.is_favourite);card.style.display=ok?'':'none';if(ok)visible.push(card)});const grid=document.querySelector('#content .grid');if(grid){visible.sort((a,b)=>{const ra=data.get(Number(a.dataset.id)),rb=data.get(Number(b.dataset.id));if(state.sort==='name')return String(ra.name||'').localeCompare(String(rb.name||''));if(state.sort==='oldest')return new Date(ra.created_at||0)-new Date(rb.created_at||0);return new Date(rb.updated_at||rb.created_at||0)-new Date(ra.updated_at||ra.created_at||0)}).forEach(c=>grid.appendChild(c));}const count=document.querySelector('#content .section-head .count');if(count)count.textContent=`${visible.length} recipes`;}
function bindCardBottoms(){document.querySelectorAll('#content .card').forEach(card=>{const body=card.querySelector('.card-body');if(body)body.style.minHeight=body.style.minHeight||'100%'});}
function newRecipe(){if(!detailDialog)return;const existingCuisines=[...new Set([...cuisines.filter(Boolean),(window.ccRecipes||[]).map(r=>r.cuisine).filter(Boolean)])].sort();createGenericEditor({dialog:detailDialog,eyebrow:'NEW RECIPE',title:'Add a recipe',fields:[{label:'Recipe name',name:'name',required:true},{group:[{label:'Cuisine',name:'cuisine',type:'select',options:existingCuisines,allowCustom:true},{label:'Course',name:'course',type:'select',options:courses,allowCustom:true}]},{label:'Recipe type',name:'recipe_type',type:'select',options:types,allowCustom:true},{label:'Servings',name:'servings'},{label:'Ingredients',name:'ingredients',type:'richtext'},{label:'Method',name:'method',type:'richtext'},{label:'My notes',name:'notes',type:'richtext'}],actions:{saveLabel:'Save'},onSave:async f=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return window.ccShowError('Please sign in again.','Sign-in required');const updates={name:editorValue(f,'name'),cuisine:editorValue(f,'cuisine',true)||null,course:editorValue(f,'course',true)||null,recipe_type:editorValue(f,'recipe_type',true)||null,servings:editorValue(f,'servings')||null,ingredients:{html:sanitizeRichHtml(f.get('ingredients')||'')},method:sanitizeRichHtml(f.get('method')||''),personal_notes:sanitizeRichHtml(f.get('notes')||'')||null,created_by:user.id,visibility:'private'};const q=await supabase.from('cc_recipes').insert(updates);if(q.error)return window.ccShowError(q.error.message,'Could not save recipe');detailDialog.close();window.location.reload()}})}
window.ccOpenNewRecipeEditor=newRecipe;
function decorate(){const content=document.querySelector('#content');if(!content||content.hidden)return;const active=document.querySelector('.tab.active')?.dataset.view||'recipes';const sig=active+':'+content.querySelector('.section-head')?.textContent+':'+content.querySelectorAll('.card').length+':'+content.querySelectorAll('.menu-card').length;if(sig===lastLibrarySignature)return;lastLibrarySignature=sig;document.querySelector('#ccLibraryTools')?.remove();document.querySelector('#ccRecipeFilters')?.remove();if(active==='recipes'){renderRecipeTools();renderRecipeFilters();applyRecipeFilters()}else if(active==='menus'){const head=content.querySelector('.section-head');if(head){const tools=document.createElement('div');tools.id='ccLibraryTools';tools.innerHTML='<div class="library-actions"><button class="secondary" id="ccImportMenus" type="button">Import menus</button><button class="primary" id="ccNewMenuContext" type="button">＋ New menu</button></div>';head.parentNode.insertBefore(tools,head);document.querySelector('#ccImportMenus').onclick=()=>document.querySelector('#importBtn')?.click();document.querySelector('#ccNewMenuContext').onclick=()=>document.querySelector('#newMenuBtn')?.click()}}bindCardBottoms()}
new MutationObserver(()=>decorate()).observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{if(e.target.closest('.tab'))setTimeout(()=>{lastLibrarySignature='';decorate()},0)});setTimeout(decorate,100);
