// Cooking Confidential: resilient auth + scalable recipe library.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const CC_SUPABASE_URL='https://yiwmtfbqbynimqvwxosu.supabase.co';
const CC_SUPABASE_KEY='sb_publishable_EG30cid4BVU1vr6EeM3f9g_hztA7Wpu';
const ccFetchNative=window.fetch.bind(window);
window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||'');if(!url.includes('supabase.co'))return ccFetchNative(input,init);const headers=new Headers(init.headers||input?.headers||{});const authorization=headers.get('authorization');if(authorization?.toLowerCase().startsWith('bearer sb_publishable_'))headers.delete('Authorization');let lastError;for(let attempt=0;attempt<2;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),9000);try{const response=await ccFetchNative(input,{...init,headers,signal:controller.signal,cache:'no-store'});clearTimeout(timer);return response}catch(error){clearTimeout(timer);lastError=error;if(attempt===0)await new Promise(resolve=>setTimeout(resolve,300));}}throw lastError};
const ccAuth=createClient(CC_SUPABASE_URL,CC_SUPABASE_KEY);
function ccSetLoginMessage(message,isError=false){const node=document.querySelector('#loginMessage');if(node){node.textContent=message;node.dataset.state=isError?'error':'ok'}}
function ccFriendlyAuthError(error){const message=String(error?.message||error||'Unable to complete sign-in.');if(/rate limit|too many requests/i.test(message))return'Please wait about 60 seconds before requesting another sign-in link.';if(/expired|invalid.*token|token.*invalid|otp_expired/i.test(message))return'This sign-in link has expired or has already been used. Please request a new link.';if(/redirect.*url|not allowed/i.test(message))return'The sign-in redirect is not configured correctly. Please try again later.';return message}
function installLoginCapture(){const form=document.querySelector('#loginForm');if(!form||form.dataset.ccAuthCapture==='1')return!!form;form.dataset.ccAuthCapture='1';form.addEventListener('submit',async event=>{event.preventDefault();event.stopImmediatePropagation();const button=form.querySelector('button');if(!button||button.disabled)return;const email=document.querySelector('#emailInput')?.value.trim();if(!email){ccSetLoginMessage('Please enter your email address.',true);return}button.disabled=true;button.textContent='Sending…';ccSetLoginMessage('Sending sign-in link…');try{const{error}=await ccAuth.auth.signInWithOtp({email,options:{emailRedirectTo:'https://cookingconfidential.in/'}});if(error)throw error;ccSetLoginMessage('Check your email for the new sign-in link.')}catch(error){console.error('Cooking Confidential sign-in:',error);ccSetLoginMessage(ccFriendlyAuthError(error),true)}finally{button.disabled=false;button.textContent='Send me a sign-in link'}},true);return true}
if(!installLoginCapture()){const observer=new MutationObserver(()=>{if(installLoginCapture())observer.disconnect()});observer.observe(document.documentElement,{subtree:true,childList:true});setTimeout(()=>observer.disconnect(),10000)}
(async()=>{const params=new URLSearchParams(window.location.search),tokenHash=params.get('token_hash'),type=params.get('type');if(!tokenHash)return;try{ccSetLoginMessage('Completing sign-in…');try{await ccAuth.auth.signOut({scope:'local'})}catch(_){}const{error}=await ccAuth.auth.verifyOtp({token_hash:tokenHash,type:type||'email'});if(error)throw error;window.history.replaceState({},document.title,window.location.pathname||'/')}catch(error){console.error('Cooking Confidential magic-link verification:',error);try{await ccAuth.auth.signOut({scope:'local'})}catch(_){}window.history.replaceState({},document.title,window.location.pathname||'/');ccSetLoginMessage(ccFriendlyAuthError(error),true);const loginPanel=document.querySelector('#loginPanel'),appPanel=document.querySelector('#appPanel');if(loginPanel)loginPanel.hidden=false;if(appPanel)appPanel.hidden=true}})();

// Paginated recipe fallback: fetch only 12 rows per page, with server-side exact count.
const PAGE_SIZE=12;let ccPage=0,ccSearch='',ccView='recipes',ccFallbackActive=false;
function esc(v=''){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function stars(n){return n?'★'.repeat(n):''}
function searchClause(q){const safe=String(q).replace(/[(),]/g,' ').replace(/[%*]/g,' ').trim();if(!safe)return'';const p=`*${safe}*`;return`(name.ilike.${p},cuisine.ilike.${p},country.ilike.${p},region.ilike.${p},course.ilike.${p},personal_notes.ilike.${p})`}
async function fetchRecipePage(page){const sessionResult=await ccAuth.auth.getSession();if(sessionResult.error)throw sessionResult.error;const session=sessionResult.data?.session;if(!session?.access_token)throw new Error('Your sign-in session is missing. Please sign in again.');const params=new URLSearchParams({select:'*',order:'updated_at.desc',limit:String(PAGE_SIZE),offset:String(page*PAGE_SIZE)});const clause=searchClause(ccSearch);if(clause)params.set('or',clause);if(ccView==='favourites')params.set('is_favourite','eq.true');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await ccFetchNative(`${CC_SUPABASE_URL}/rest/v1/cc_recipes?${params}`,{headers:{apikey:CC_SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,Prefer:'count=exact'},signal:controller.signal,cache:'no-store'});const text=await response.text();if(!response.ok)throw new Error(text||`Recipe request failed (${response.status}).`);const data=JSON.parse(text||'[]');const range=response.headers.get('content-range')||'';const match=range.match(/\/([0-9]+|\*)$/);const total=match&&match[1]!=='*'?Number(match[1]):page*PAGE_SIZE+data.length;return{data,total}}finally{clearTimeout(timer)}}
function pagination(total){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));ccPage=Math.min(ccPage,pages-1);const start=total?ccPage*PAGE_SIZE+1:0,end=Math.min((ccPage+1)*PAGE_SIZE,total);return`<div class="cc-pagination" style="display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;margin:24px 0 8px"><button class="secondary cc-page" data-page="0" ${ccPage===0?'disabled':''}>First</button><button class="secondary cc-page" data-page="${ccPage-1}" ${ccPage===0?'disabled':''}>‹ Prev</button><span style="padding:0 8px;color:#746f66;font-size:14px">${start}–${end} of ${total} · Page ${ccPage+1} of ${pages}</span><button class="secondary cc-page" data-page="${ccPage+1}" ${ccPage>=pages-1?'disabled':''}>Next ›</button><button class="secondary cc-page" data-page="${pages-1}" ${ccPage>=pages-1?'disabled':''}>Last</button></div>`}
function renderPage(data,total){const content=document.querySelector('#content');if(!content)return;content.innerHTML=`<div class="section-head"><h2>${ccView==='favourites'?'Favourites':'Your recipes'}</h2><span class="count">${total} recipes</span></div>${data.length?'<div class="grid">'+data.map(r=>`<article class="card"><div class="card-image">🍽</div><div class="card-body"><span class="tag">${esc(r.cuisine||'Uncategorised')}</span><h3>${esc(r.name||'Untitled recipe')}</h3><div class="meta">${esc(r.course||'Recipe')} · ${stars(r.rating)}</div></div></article>`).join('')+'</div>':`<div class="empty">No recipes found. Try another search.</div>`}${pagination(total)}`;content.querySelectorAll('.cc-page').forEach(b=>b.onclick=async()=>{if(!b.disabled){ccPage=Number(b.dataset.page);await loadPage()}})}
async function loadPage(){const content=document.querySelector('#content');if(!content)return;content.innerHTML='<div class="empty">Loading your recipes…</div>';try{const result=await fetchRecipePage(ccPage);ccFallbackActive=true;renderPage(result.data,result.total)}catch(error){console.error('Cooking Confidential paginated recipe load:',error);content.innerHTML=`<div class="empty"><strong>We could not load the recipe library.</strong><br><small>${esc(error?.message||error)}</small></div>`}}
setTimeout(async()=>{const content=document.querySelector('#content'),app=document.querySelector('#appPanel');if(content&&!app?.hidden&&/Loading your recipes/i.test(content.textContent||''))await loadPage()},3500);
document.addEventListener('input',event=>{if(event.target?.id==='searchInput'&&ccFallbackActive){clearTimeout(window.__ccSearchTimer);window.__ccSearchTimer=setTimeout(()=>{ccSearch=event.target.value.trim();ccPage=0;loadPage()},250)}},true);
document.addEventListener('click',event=>{const tab=event.target.closest('.tab');if(!tab)return;const view=tab.dataset.view;if(view==='recipes'||view==='favourites')setTimeout(()=>{if(ccFallbackActive){ccView=view;ccPage=0;loadPage()}},80)},true);
