// Independent recipe-library toolbar. No dependencies on other feature modules.
const state={filter:'latest'};let lastAppliedSignature='';
const css=document.createElement('style');
css.textContent=`#importBtn,#addRecipeBtn{display:none!important}#ccLibraryTools{display:block!important;position:relative;z-index:20;margin:0 0 7px}.cc-library-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px}.cc-library-actions{display:flex;gap:7px;align-items:center}.cc-library-icon{width:44px!important;height:40px!important;padding:0!important;display:grid!important;place-items:center!important;font-size:23px!important;line-height:1!important}.cc-library-filter{display:block!important;margin:0!important;min-width:140px;max-width:46vw}.cc-library-filter span{display:none}.cc-library-filter select{width:100%;border:1px solid var(--line);border-radius:9px;background:var(--card);color:var(--ink);padding:8px 10px;font:13px Arial}@media(max-width:760px){.hero{padding:8px 18px 6px!important}.hero .eyebrow{margin-bottom:5px!important}.hero h1{margin-bottom:6px!important}.search-wrap{margin-top:8px!important}.tab{padding:8px 0!important}#content{padding:4px 18px!important}.section-head{margin-bottom:6px!important}}
`;
document.head.appendChild(css);
function esc(s=''){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function values(field){return [...new Set((window.ccRecipes||[]).map(r=>String(r?.[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function options(){const out=[['latest','Latest'],['favourite','Favourites']];[['cuisine','Cuisine'],['course','Course'],['recipe_type','Recipe type'],['country','Country / Region'],['region','Country / Region']].forEach(([field,label])=>values(field).forEach(v=>{if(!out.some(x=>x[0]===`${field}:${v}`))out.push([`${field}:${v}`,`${label}: ${v}`])}));return out}
function librarySignature(){return [...document.querySelectorAll('#content .card')].map(c=>c.dataset.id||'').sort().join(',')+'|'+state.filter}function ensure(){const content=document.querySelector('#content');if(!content||content.hidden)return;const active=document.querySelector('.tab.active')?.dataset.view||'recipes';const head=content.querySelector('.section-head');if(!head)return;if(active!=='recipes'){document.querySelector('#ccLibraryTools')?.remove();lastAppliedSignature='';return}let tools=document.querySelector('#ccLibraryTools');if(tools){const sig=librarySignature();if(sig!==lastAppliedSignature){apply();lastAppliedSignature=sig}return}if(!tools){tools=document.createElement('div');tools.id='ccLibraryTools';head.parentNode.insertBefore(tools,head)}tools.innerHTML=`<div class="cc-library-toolbar"><div class="cc-library-actions"><button class="secondary cc-library-icon" id="ccImportRecipes" type="button" aria-label="Import recipes" title="Import recipes">⇅</button><button class="primary cc-library-icon" id="ccNewRecipe" type="button" aria-label="New recipe" title="New recipe">＋</button></div><label class="cc-library-filter"><span>Filter</span><select id="ccRecipeFilter" aria-label="Filter recipes">${options().map(([v,l])=>`<option value="${esc(v)}" ${v===state.filter?'selected':''}>${esc(l)}</option>`).join('')}</select></label></div>`;
tools.querySelector('#ccImportRecipes').onclick=()=>document.querySelector('#importBtn')?.click();
tools.querySelector('#ccNewRecipe').onclick=()=>window.ccOpenNewRecipeEditor?.();
tools.querySelector('#ccRecipeFilter').onchange=e=>{state.filter=e.target.value;apply()};
apply();
}
function apply(){const cards=[...document.querySelectorAll('#content .card')];const data=new Map((window.ccRecipes||[]).map(r=>[Number(r.id),r]));const [kind,...rest]=state.filter.split(':');const value=rest.join(':');const visible=[];cards.forEach(card=>{const r=data.get(Number(card.dataset.id));if(!r)return;let ok=true;if(kind==='favourite')ok=!!r.is_favourite;if(kind==='cuisine')ok=r.cuisine===value;if(kind==='course')ok=r.course===value;if(kind==='recipe_type')ok=r.recipe_type===value;if(kind==='country')ok=r.country===value||r.region===value;if(kind==='region')ok=r.region===value;card.style.display=ok?'':'none';if(ok)visible.push(card)});const grid=document.querySelector('#content .grid');if(grid){const sorted=visible.sort((a,b)=>{const ra=data.get(Number(a.dataset.id)),rb=data.get(Number(b.dataset.id));if(state.filter==='latest')return new Date(rb.updated_at||rb.created_at||0)-new Date(ra.updated_at||ra.created_at||0);return String(ra.name||'').localeCompare(String(rb.name||''))});sorted.forEach((c,i)=>{if(grid.children[i]!==c)grid.insertBefore(c,grid.children[i]||null)})}const count=document.querySelector('#content .section-head .count');if(count)count.textContent=`${visible.length} recipes`}
new MutationObserver(()=>requestAnimationFrame(ensure)).observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{if(e.target.closest('.tab'))setTimeout(()=>{state.filter='latest';ensure()},0)});window.addEventListener('cc:recipes-loaded',()=>setTimeout(ensure,0));setTimeout(ensure,250);
