const PAGE_W = 210;
const MARGIN = 18;
const FOOTER_Y = 286;
function clean(value=''){return String(value??'').trim()}
function ingredientLines(recipe){return Array.isArray(recipe?.ingredients)?recipe.ingredients.map(x=>typeof x==='string'?clean(x):[x.quantity,x.unit,x.name].filter(Boolean).join(' ')).filter(Boolean):[]}
function safeFileName(name){return clean(name||'recipe').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'recipe'}
function escHtml(value=''){return String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function recipeData(recipeOverride=null){const r=recipeOverride||window.ccCurrentRecipe;if(!r)throw new Error('No recipe is currently open.');return{name:clean(r.name),cuisine:clean(r.cuisine),course:clean(r.course),rating:r.rating||0,ingredients:ingredientLines(r),method:clean(r.method),notes:clean(r.personal_notes),sourceTitle:clean(r.source_title),sourceUrl:clean(r.source_url)}}
function addLogo(doc){doc.setDrawColor(155,63,47);doc.setLineWidth(.45);doc.circle(MARGIN+5,13,5,'S');doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.setTextColor(155,63,47);doc.text('CC',MARGIN+5,15.1,{align:'center'})}
function addHeader(doc,recipe){addLogo(doc);doc.setTextColor(36,35,31);doc.setFont('times','bold');doc.setFontSize(11);doc.text('Cooking Confidential',MARGIN+14,14.5);doc.setDrawColor(221,214,202);doc.setLineWidth(.25);doc.line(MARGIN,21,210-MARGIN,21);doc.setFont('times','normal');doc.setFontSize(8);doc.setTextColor(119,115,106);doc.text(recipe.name,210-MARGIN,14.5,{align:'right'})}
function addFooter(doc,pageNo){doc.setDrawColor(221,214,202);doc.setLineWidth(.25);doc.line(MARGIN,279,210-MARGIN,279);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(119,115,106);doc.text('Cooking Confidential · Private recipe collection',MARGIN,FOOTER_Y);doc.text('Good Food Well Remembered',210-MARGIN,FOOTER_Y,{align:'right'});doc.text(String(pageNo),105,FOOTER_Y,{align:'center'})}
function addSection(doc,title,lines,state){if(!lines.length)return;const ensure=h=>{if(state.y+h>272){addFooter(doc,state.page);doc.addPage();state.page++;addHeader(doc,state.recipe);state.y=30}};ensure(12);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(155,63,47);doc.text(title,MARGIN,state.y);state.y+=7;doc.setFont('times','normal');doc.setFontSize(10.5);doc.setTextColor(36,35,31);for(const line of lines){const wrapped=doc.splitTextToSize(line,210-MARGIN*2-6);ensure(wrapped.length*5+2);doc.text('•',MARGIN,state.y);doc.text(wrapped,MARGIN+5,state.y);state.y+=wrapped.length*5+2}state.y+=5}
async function buildPdf(recipeOverride=null){const recipe=recipeData(recipeOverride);const{jsPDF}=await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm');const doc=new jsPDF({unit:'mm',format:'a4',putOnlyUsedFonts:true});const state={page:1,y:30,recipe};addHeader(doc,recipe);doc.setFont('times','normal');doc.setTextColor(36,35,31);doc.setFontSize(25);const titleLines=doc.splitTextToSize(recipe.name,210-MARGIN*2);doc.text(titleLines,MARGIN,state.y);state.y+=titleLines.length*10+3;const meta=[recipe.cuisine,recipe.course,recipe.rating?'★'.repeat(recipe.rating):''].filter(Boolean).join(' · ');if(meta){doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(119,115,106);doc.text(meta,MARGIN,state.y);state.y+=10}addSection(doc,'Ingredients',recipe.ingredients,state);if(recipe.method)addSection(doc,'Method',recipe.method.split(/\r?\n+/).map(clean).filter(Boolean),state);if(recipe.notes)addSection(doc,'My notes',recipe.notes.split(/\r?\n+/).map(clean).filter(Boolean),state);if(recipe.sourceTitle||recipe.sourceUrl)addSection(doc,'Source',[recipe.sourceTitle||recipe.sourceUrl],state);addFooter(doc,state.page);return{doc,recipe}}
async function exportPdf(recipeOverride=null){const{doc,recipe}=await buildPdf(recipeOverride);doc.save(`${safeFileName(recipe.name)}.pdf`)}
async function shareRecipe(recipeOverride=null){const{doc,recipe}=await buildPdf(recipeOverride);const blob=doc.output('blob');const file=new File([blob],`${safeFileName(recipe.name)}.pdf`,{type:'application/pdf'});const canNativeShare=!!navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}));if(canNativeShare){const isDesktop=navigator.maxTouchPoints===0&&!/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);let pdfUrl=null;if(isDesktop){pdfUrl=URL.createObjectURL(blob);window.open(pdfUrl,'_blank','noopener,noreferrer')}try{await navigator.share({title:recipe.name,text:'Shared from Cooking Confidential',files:[file]})}finally{if(pdfUrl)setTimeout(()=>URL.revokeObjectURL(pdfUrl),60000)}return}doc.save(file.name)}
function printRecipe(recipeOverride=null){const r=recipeData(recipeOverride);const ingredients=r.ingredients.map(x=>`<li>${escHtml(x)}</li>`).join('');const method=r.method?r.method.split(/\r?\n+/).map(clean).filter(Boolean).map(x=>`<p>${escHtml(x)}</p>`).join(''):'<p>—</p>';const notes=r.notes?`<section><h3>My notes</h3>${r.notes.split(/\r?\n+/).map(clean).filter(Boolean).map(x=>`<p>${escHtml(x)}</p>`).join('')}</section>`:'';const meta=[r.cuisine,r.course,r.rating?'★'.repeat(r.rating):''].filter(Boolean).join(' · ');const win=window.open('','_blank');if(!win){window.ccShowError?.('Please allow pop-ups for Cooking Confidential to open the print view.','Print view blocked');return}win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escHtml(r.name)} · Cooking Confidential</title><style>@page{size:A4;margin:18mm 18mm 20mm}body{margin:0;background:#fff;color:#24231f;font-family:Georgia,"Times New Roman",serif}.toolbar{position:sticky;top:0;display:flex;justify-content:flex-end;gap:8px;padding:12px 0;border-bottom:1px solid #ddd6ca;background:#fff}.toolbar button{border:1px solid #ddd6ca;border-radius:8px;background:#f6f1e8;padding:9px 16px;font:600 12px Arial;color:#24231f;cursor:pointer}.toolbar .print{background:#9b3f2f;color:#fff;border-color:#9b3f2f}.page{max-width:174mm;margin:0 auto}.header{display:flex;align-items:center;gap:10px;border-bottom:1px solid #ddd6ca;padding:14px 0 9px}.logo{width:28px;height:28px;border:1px solid #9b3f2f;border-radius:50%;display:grid;place-items:center;color:#9b3f2f;font:600 9px Arial}.brand{font:bold 14px Georgia}.tag{font:10px Arial;letter-spacing:.1em;text-transform:uppercase;color:#9b3f2f;margin-top:22px}.title{font-size:30px;font-weight:400;line-height:1.1;margin:7px 0}.meta{font:11px Arial;color:#77736a;margin-bottom:24px}section{margin-top:22px}h3{font:600 10px Arial;text-transform:uppercase;letter-spacing:.12em;color:#9b3f2f}li,p{font-size:11pt;line-height:1.55}li{margin-bottom:5px}footer{position:fixed;left:0;right:0;bottom:0;border-top:1px solid #ddd6ca;padding-top:7px;font:9px Arial;color:#77736a;display:flex;justify-content:space-between}footer span:last-child{color:#24231f}@media print{.toolbar{display:none}.page{max-width:none}}</style></head><body><div class="page"><div class="toolbar"><button onclick="window.close()">Exit</button><button class="print" onclick="window.print()">Print</button></div><header class="header"><span class="logo">CC</span><span class="brand">Cooking Confidential</span></header><div class="tag">Recipe</div><h1 class="title">${escHtml(r.name)}</h1><div class="meta">${escHtml(meta)}</div><section><h3>Ingredients</h3><ul>${ingredients||'<li>—</li>'}</ul></section><section><h3>Method</h3>${method}</section>${notes}</div><footer><span>Cooking Confidential · Private recipe collection</span><span>Good Food Well Remembered</span></footer></body></html>`);win.document.close();win.focus()}
function attachDetailButtons(){const content=document.querySelector('#detailContent');const actions=content?.querySelector('.detail-actions');if(!actions||!content.querySelector('.detail-title')||actions.dataset.outputReady==='1')return;actions.dataset.outputReady='1';const shareBtn=document.createElement('button');shareBtn.type='button';shareBtn.className='secondary';shareBtn.id='ccShareRecipe';shareBtn.textContent='Share';shareBtn.onclick=()=>shareRecipe().catch(e=>window.ccShowError?.(e.message||String(e),'Could not share recipe'));const printBtn=document.createElement('button');printBtn.type='button';printBtn.className='secondary';printBtn.id='ccPrintRecipe';printBtn.textContent='Print';printBtn.onclick=()=>{try{printRecipe()}catch(e){window.ccShowError?.(e.message||String(e),'Could not print recipe')}};actions.append(shareBtn,printBtn)}
const observer=new MutationObserver(attachDetailButtons);observer.observe(document.body,{subtree:true,childList:true});attachDetailButtons();window.ccRecipeOutput={exportPdf,shareRecipe,printRecipe};
