import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://yiwmtfbqbynimqvwxosu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_EG30cid4BVU1vr6EeM3f9g_hztA7Wpu';
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let pdfPromise,tessPromise;
const clean=s=>String(s??'').replace(/[\u0000-\u001F\u007F\uFFFD]/g,' ').replace(/[®©™]/g,' ').replace(/[ \t]+/g,' ').trim();
const lines=s=>String(s??'').replace(/\r/g,'').split('\n').map(clean).filter(x=>x.length>1);
function loadPdf(){if(pdfPromise)return pdfPromise;pdfPromise=import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs').then(pdf=>{pdf.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';return pdf});return pdfPromise}
function loadTesseract(){if(tessPromise)return tessPromise;tessPromise=new Promise((resolve,reject)=>{if(window.Tesseract?.createWorker)return resolve(window.Tesseract);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=()=>window.Tesseract?.createWorker?resolve(window.Tesseract):reject(new Error('Image reader loaded without OCR support.'));s.onerror=()=>reject(new Error('Could not load the image reader on this browser.'));document.head.appendChild(s)});return tessPromise}
async function signedBlob(item){const path=item.file_path||item.original_file_path;if(!path)throw Error('Uploaded PDF path is missing.');const{data,error}=await sb.storage.from('cooking-confidential').createSignedUrl(path,600);if(error||!data?.signedUrl)throw Error(error?.message||'Could not read the uploaded PDF.');const r=await fetch(data.signedUrl);if(!r.ok)throw Error('Could not load the uploaded PDF.');return r.blob()}
function setProgress(text){const d=document.querySelector('#detailContent');if(d){const p=d.querySelector('.cc-pdf-progress');if(p)p.textContent=text}}
function normaliseOcr(text){let a=lines(text);a=a.map(x=>x.replace(/^[-•·*]+\s*/,'').replace(/\s*\|\s*/g,' ').replace(/\bIbs\b/gi,'lbs').replace(/\bIb\b/gi,'lb').replace(/\b1\s*\/\s*2\b/g,'½').replace(/\b1\s*\/\s*4\b/g,'¼').replace(/\b3\s*\/\s*4\b/g,'¾').replace(/\s{2,}/g,' ').trim()).filter(Boolean);const out=[];for(const x of a){if(out.some(y=>y.toLowerCase()===x.toLowerCase()))continue;out.push(x)}return out}
const SECTION=/^(ingredients?|ingredient list|what you need|method|directions?|instructions?|preparation|steps?|procedure|servings?|notes?|tips?|storage|serving suggestions?)\s*[:\-–—,]?\s*$/i;
const GARBAGE=/^(?:#\w+\s*)+$|^[^A-Za-z0-9]{0,4}$|^(?:like|comment|share|send|home|video|friends|marketplace|notifications|menu|follow|save|add a comment|see more|suggested for you|sponsored|original audio|reels?)$/i;
const TITLE_GENERIC=/^(recipe|recipes|ingredients?|method|directions?|instructions?|preparation|steps?|procedure|contents?|index|introduction|notes?|tips?|storage|serving suggestions?)$/i;
function titleScore(x){const t=clean(x).replace(/^[^A-Za-z]+/,'').replace(/[✨⭐🌟]+/g,'').trim();if(!t||TITLE_GENERIC.test(t)||GARBAGE.test(t)||t.length>100)return -1;let score=0;if(/\b(sauce|dip|dressing|curry|chutney|marinade|rub|paste|bread|cake|salad|soup|rice|chicken|fish|meat|pasta|dessert|cocktail)\b/i.test(t))score+=5;if(t.length<=60)score+=2;if(/\([^)]{2,60}\)/.test(t))score+=2;if((t.match(/[A-Za-z]/g)||[]).length>=4)score+=1;if(/^by\s+/i.test(t))score-=4;return score}
function mergeIngredientWraps(list){const out=[];for(const raw of list){const v=clean(raw);if(!v)continue;const startsAmount=/^(?:\d|½|⅓|⅔|¼|¾|one|two|three|four|five|six|seven|eight|nine|ten|a\s+)/i.test(v);if(out.length&&!startsAmount){const prev=out[out.length-1];if(/\b(?:teaspoon|tablespoon|tbsp|tsp|cup|cups|oz|lb|lbs|g|kg|ml|l)\b/i.test(prev)||/\b(?:salt|oil|vinegar|mustard|mayonnaise|honey|pepper|sugar|flour|water|milk|cream|shallot|garlic|onion)\b/i.test(prev))out[out.length-1]=`${prev} ${v}`;else out.push(v)}else out.push(v)}return out}
function mergeMethodWraps(list){const out=[];for(const x of list){const v=clean(x);if(!v)continue;const startsStep=/^(?:\d+\.\s*|(?:combine|mix|stir|whisk|blend|process|add|pour|heat|cook|bake|roast|grill|marinate|season|simmer|boil|fry|serve|refrigerate|chill|place|remove|transfer|taste|adjust|dissolve)\b)/i.test(v);if(out.length&&!startsStep)out[out.length-1]=`${out[out.length-1]} ${v}`;else out.push(v)}return out}
function deriveRecipe(text,fileName){
 const a=cleanGarbage(normaliseOcr(text));
 const ih=a.findIndex(x=>/^ingredients?(?:\s+list)?\s*[:\-–—,]?\s*$/i.test(x));
 const mh=a.findIndex(x=>/^(?:method|directions?|instructions?|preparation|steps?|procedure)\s*[:\-–—,]?\s*$/i.test(x));
 const endForIngredients=mh>ih&&ih>=0?mh:a.length;
 let ingredients=ih>=0?a.slice(ih+1,endForIngredients):a.filter(x=>/^(?:[-•·]\s*)?(?:\d|½|⅓|⅔|¼|¾|one|two|three|four|five|a\s+)/i.test(x)).slice(0,200);
 let method=mh>=0?a.slice(mh+1):[];
 ingredients=ingredients.filter(x=>!SECTION.test(x)&&!/^\d?\s*[®©™]+\s*\w*$/i.test(x));
 ingredients=mergeIngredientWraps(ingredients).slice(0,200);
 method=mergeMethodWraps(method.filter(x=>!SECTION.test(x))).join('\n').trim();
 const baseName=clean(String(fileName||'Imported recipe').replace(/\.[^.]+$/,'').replace(/[_-]+/g,' '))||'Imported recipe';
 const pre=ih>0?a.slice(0,ih):a.slice(0,Math.min(12,a.length));
 const desc=pre.find(x=>/^(?:a\s+|an\s+|the\s+)?(?:tangy|rich|spicy|sweet|refreshing|classic|simple|savory|creamy|zesty)\b/i.test(x))||'';
 const lower=baseName.toLowerCase();
 const cuisine=/japanese|italian|mexican|indian|thai|chinese|korean|french|greek|spanish|mediterranean|american/i.exec(`${baseName} ${desc}`)?.[0]||'';
 const course=/\b(sauce|dip|dressing|marinade|rub|paste|chutney|bread|cake|salad|soup|dessert|beverage)\b/i.exec(lower)?.[0]||'';
 const servingLine=pre.find(x=>/^(?:serves|makes|yield)\b/i.test(x))||'';
 const servings=servingLine.replace(/^(?:serves|makes|yield)\s*/i,'').trim();
 return{name:baseName,description:desc,ingredients,method,cuisine,course,servings,raw_text:a.join('\n')};
}
function cleanGarbage(a){const out=[];for(const x of a){const t=clean(x);if(!t||GARBAGE.test(t)||/^#\w+/.test(t))continue;if(/^(?:recipe by|stay tuned for|we love sharing|follow for more|thanks for watching|subscribe for more)/i.test(t))continue;out.push(t)}return out}
export async function ocrScannedPdf(id){const{data:item,error}=await sb.from('cc_import_items').select('*').eq('id',id).single();if(error||!item)throw Error(error?.message||'Import item not found.');const blob=await signedBlob(item);const pdfjs=await loadPdf();const pdf=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer())}).promise;const T=await loadTesseract();const worker=await T.createWorker('eng');let full=[];try{for(let i=1;i<=pdf.numPages;i++){setProgress(`Reading scanned page ${i} of ${pdf.numPages}…`);const page=await pdf.getPage(i);const base=page.getViewport({scale:2.6});const canvas=document.createElement('canvas');canvas.width=Math.ceil(base.width);canvas.height=Math.ceil(base.height);const ctx=canvas.getContext('2d',{willReadFrequently:true});await page.render({canvasContext:ctx,viewport:base}).promise;await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1',user_defined_dpi:'300'});const r=await worker.recognize(canvas);full.push(r.data.text||'');canvas.width=1;canvas.height=1}}finally{await worker.terminate()}const text=full.join('\n');if(!text.trim())throw Error('OCR could not find readable text in the scanned PDF.');const recipe=deriveRecipe(text,item.file_name||'Scanned recipe');const payload={version:4,scanned_pdf:true,recipe,raw_text:text};const{error:ue}=await sb.from('cc_import_items').update({extracted_text:JSON.stringify(payload),source_title:recipe.name,extraction_status:'ready',review_status:'pending',error_message:null}).eq('id',id);if(ue)throw Error(ue.message);return{item:{...item,extracted_text:JSON.stringify(payload),source_title:recipe.name,extraction_status:'ready',review_status:'pending'},recipe};}
